### ISSUE TITLE
serve all static assets from current folder, not just index.html

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-store-server#7]
follow up for #1 

See the [serve-static](https://github.com/expressjs/serve-static) middleware for ExpressJS

**Comment by inchikutty** [comment]
Hey Greg, share your thoughts on pull request at https://github.com/hoodiehq/pouchdb-hoodie-store-server/pull/8

**Comment by gr2m** [comment]
done via #8
